blog/urls.py
# coding: utf-8
# Module: urls
# Created on: 17.11.2015
# Author: Roman Miroshnychenko aka Roman V.M. (romanvm@yandex.ua)

from django.conf.urls import url

from .apps import BlogAppConfig
from .feeds import RecentPostsRSSFeed, RecentPostsAtomFeed
from .views import (BlogHomeView, BlogPostView, BlogFeaturedPostsView,
                    BlogCategoryView, BlogCategoriesListView,
                    BlogArchiveView, BlogMonthArchiveView, BlogPostSearchView)

app_name = BlogAppConfig.name

urlpatterns = [
    url(r'^post/(?P<slug>[\w-]+)-(?P<pk>\d+)/$', BlogPostView.as_view(), name='post'),
    url(r'^featured/$', BlogFeaturedPostsView.as_view(), name='featured_posts'),
    url(r'^categories/(?P<slug>[\w-]+)/$', BlogCategoryView.as_view(), name='category'),
    url(r'^categories/$', BlogCategoriesListView.as_view(), name='categories_list'),
    url(r'^archive/(?P<year>\d{4})-(?P<month>\d{1,2})/$', BlogMonthArchiveView.as_view(), name='month_archive'),
    url(r'^archive/$', BlogArchiveView.as_view(), name='archive'),
    url(r'^search/', BlogPostSearchView.as_view(), name='search'),
    url(r'^feed/rss/$', RecentPostsRSSFeed(), name='rss_feed'),
    url(r'^feed/atom/$', RecentPostsAtomFeed(), name='atom_feed'),
    url(r'^$', BlogHomeView.as_view(), name='home'),
]

romans_blog/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from django.utils.translation import ugettext as _
from django.db.utils import DatabaseError
from filebrowser.sites import site
from blog.sitemaps import BlogPostsSiteMap
from pages.sitemaps import PagesSiteMap
from common_content.utils import get_site_config
from common_content.views import robots_txt

sitemaps = {
    'blog': BlogPostsSiteMap,
    'pages': PagesSiteMap,
            }
try:
    # Translators: The placeholder represents a site's name
    admin.site.site_header = _('{0} Administration').format(get_site_config().site_name)
except DatabaseError:  # This is to run migrate when site_config table has not been created yet.
    pass

urlpatterns = [
    url(r'^admin/filebrowser/', include(site.urls[:2])),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^admin/', include(admin.site.urls[:2])),
    url(r'^robots.txt$', robots_txt, name='robots'),
    url(r'^sitemap.xml$', sitemap, {'sitemaps': sitemaps}, name='sitemap'),
    url(r'^pages/', include('pages.urls', namespace='pages')),
    url(r'', include('blog.urls', namespace='blog')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns.insert(0, url(r'^__debug__/', include(debug_toolbar.urls)))

bootstrap4_skin/templates/bootstrap4_skin/base.html
{% load i18n %}
{% load static %}
{% load common_tags %}
{% load blog_tags %}
{% load pages_tags %}
{% get_current_language as LANGUAGE_CODE %}
{% get_site_config as site_config %}
{% url "blog:home" as home_url %}
<!doctype html>
<html lang="{{ LANGUAGE_CODE }}" class="h-100">
  <head>
    {% block meta %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="robots" content="index,follow">
    {% site_json_ld %}
    {% endblock meta %}

    {% block title %}
    {% endblock title %}

    {% if site_config.site_logo %}
    <link rel="icon" type="image/png" href="{{ site_config.site_logo.url }}">
    {% else %}
    <link rel="icon" type="image/png" href="{% static "bootstrap4_skin/img/favicon.png" %}">
    <link rel="icon" type="image/x-icon" href="{% static "bootstrap4_skin/img/favicon.ico" %}">
    {% endif %}
    {% block css %}
    <link rel="stylesheet" href="{% static "bootstrap4_skin/css/bootstrap.min.css" %}">
    <link rel="stylesheet" href="{% static "bootstrap4_skin/css/fontawesome-all.min.css" %}">
    <link rel="stylesheet" href="{% static "common_content/css/prism.css" %}">
    <link rel="stylesheet" href="{% static "bootstrap4_skin/css/styles.css" %}">
    {% endblock css %}

    {% block featured_image %}
    {% endblock featured_image %}

    {% block js %}
    <script src="{% static "bootstrap4_skin/js/jquery-3.3.1.min.js" %}"></script>
    <script src="{% static "bootstrap4_skin/js/popper.min.js" %}"></script>
    <script src="{% static "bootstrap4_skin/js/skin.js" %}"></script>
    {% endblock js %}

    {% if not user.is_authenticated %}
    {% include "common_content/google_analytics.html" %}
    {% endif %}
    <link title="{{ site_config.site_name }} - {% trans "Recent Posts" %}" rel="alternate"
        type="application/rss+xml" href="{% url "blog:rss_feed" %}">
  </head>
  <body class="h-100 d-flex flex-column">
    <header>
      {% block navbar %}
      <nav class="navbar navbar-expand-lg navbar-dark font-weight-bold">
        <div class="container">
          <a class="navbar-brand" href="{{ home_url }}"><i class="fas fa-desktop"></i>&nbsp;{{ site_config.site_name }}</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
              aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse justify-content-between" id="navbarNav">
            <ul class="navbar-nav">
              {# Blog menu links #}
              {% get_blog_menu_links as blog_menu_links %}
              {% check_blog_url as is_blog_url %}
              <li class="nav-item dropdown {% if is_blog_url %}active{% endif %}">
                <a class="nav-link dropdown-toggle" href="{{ home_url }}" id="navbarDropdown"
                    role="button" data-toggle="dropdown"
                    aria-haspopup="true" aria-expanded="false">
                  {% trans "Blog" %}
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  {% for blog_link in blog_menu_links %}
                  {% if blog_link.url %}
                  <a class="dropdown-item" href="{{ blog_link.url }}">{{ blog_link.caption }}</a>
                  {% endif %}
                  {% endfor %}
                </div>
              </li>
              {# Pages menu links #}
              {% get_pages_menu_links as pages_menu_links %}
              {% for menu_link in pages_menu_links %}
              <li class="nav-item {% if request.path == menu_link.get_absolute_url %}active{% endif %}">
                <a class="nav-link" href="{{ menu_link.get_absolute_url }}">{{ menu_link.caption }}</a>
              </li>
              {% endfor %}
            </ul>
            <div>
              {% if site_config.facebook %}
              <a href="{{ site_config.facebook }}" class="btn btn-secondary btn-sm btn-social"><i class="fab fa-facebook"></i></a>
              {% endif %}
              {% if site_config.twitter %}
              <a href="{{ site_config.twitter }}" class="btn btn-secondary btn-sm btn-social"><i class="fab fa-twitter"></i></a>
              {% endif %}
              {% if site_config.linkedin %}
              <a href="{{ site_config.linkedin }}" class="btn btn-secondary btn-sm btn-social"><i class="fab fa-linkedin"></i></a>
              {% endif %}
              {% if site_config.github %}
              <a href="{{ site_config.github }}" class="btn btn-secondary btn-sm btn-social"><i class="fab fa-github"></i></a>
              {% endif %}
              {% if site_config.stackoverflow %}
              <a href="{{ site_config.stackoverflow }}" class="btn btn-secondary btn-sm btn-social"><i class="fab fa-stack-overflow"></i></a>
              {% endif %}
            </div>
          </div>
        </div>
      </nav>
      {% endblock navbar %}

      <div class="header-background d-flex align-items-center justify-content-center">
        <div class="header-content text-white text-center">

          {% block header %}
          {% endblock header %}

        </div>
      </div>

    </header>

    <main class="flex-fill">
      <div class="container mt-3">
        <div class="row">

        {% block content %}
        {% endblock content %}

        </div>
      </div>
    </main>

    {% block footer %}
    <footer class="bg-dark d-flex align-items-center">
      <div class="container">
        <div class="row text-white">
          <div class="col-md-7 offset-md-1 mt-2 mb-1">
            <p>
              <small>
                Boostrap 4 skin for Roman&apos;s blog,
                &copy; <a href="https://github.com/romanvm" class="text-light">Roman Miroshnychenko</a>.<br>
                Design elements by <a href="http://getbootstrap.com/" target="_blank" class="text-light">Bootstrap</a> and
                <a href="https://fortawesome.github.io/Font-Awesome/" target="_blank" class="text-light">Font Awesome</a>.
            </small>
            </p>
          </div>
          <div class="col-md-3 mt-2 mb-1">
            <p class="mt-2">
              <a href="http://www.djangoproject.com/">
                <img src="https://www.djangoproject.com/m/img/badges/djangosite100x25_grey.gif"
                  border="0" alt="A Django site." title="A Django site." />
              </a>
            </p>
          </div>
        </div>
      </div>
    </footer>
    {% endblock footer %}

    <script src="{% static "bootstrap4_skin/js/bootstrap.min.js" %}"></script>
    <script src="{% static "common_content/js/prism.min.js" %}"></script>
    <script src="{% static "common_content/js/prism-django.min.js" %}"></script>
  </body>
</html>

bootstrap4_skin/templates/bootstrap4_skin/blog_archive.html
{% extends "bootstrap4_skin/blog_posts_list.html" %}
{% load i18n %}
{% load static %}
{% load common_tags %}

{% block featured_image %}
<style>
  header {
    background-image: url('{% static "bootstrap4_skin/img/featured/archive.jpg" %}');
  }
</style>
{% endblock featured_image %}

{% block header %}
<h1 class="display-1">{{ page_title }}</h1>
{% endblock header %}

{% block blog_list %}
{% if months %}
  <div class="row">
    {% regroup months by year as months_list %}
      {% for month in months_list %}
      <div class="col-sm-2">
        <h3>{{ month.grouper }}</h3>
        {% for item in month.list %}
        <p>
          <a href="{% url "blog:month_archive" year=item.year month=item.month %}">
            {{ item|date:"F" }}
          </a>
        </p>
        {% endfor %}
      </div>
      {% endfor %}
  </div>
{% else %}
  <p class="text-danger">{% trans "This blog has no posts." %}</p>
{% endif %}
{% endblock blog_list %}

bootstrap4_skin/templates/bootstrap4_skin/blog_categories_list.html
{% extends "bootstrap4_skin/blog_posts_list.html" %}
{% load i18n %}
{% load static %}

{% block featured_image %}
<style>
  header {
    background-image: url('{% static "bootstrap4_skin/img/featured/categories.jpg" %}');
  }
</style>
{% endblock featured_image %}

{% block header %}
<h1 class="display-1">{{ page_title }}</h1>
{% endblock header %}

{% block blog_list %}
  <div class="categories-list">
  {% if categories %}
    <ul>
      {% for category in categories %}
        <li>
          <a href="{{ category.get_absolute_url }}">{{ category.name }}&nbsp;
            <span class="badge badge-secondary">{{ category.posts.count }}</span>
          </a>
        </li>
      {% endfor %}
    </ul>
  {% else %}
    <p class="text-danger">{% trans "No categories defined!" %}</p>
  {% endif %}
  </div>
{% endblock blog_list %}

bootstrap4_skin/templates/bootstrap4_skin/blog_post.html
{% extends "bootstrap4_skin/base.html" %}
{% load i18n %}
{% load static %}
{% load common_tags %}
{% load blog_tags %}
{% get_site_config as site_config %}

{% block meta %}
  {{ block.super }}
  {% if post.categories.count %}
  <meta name="keywords" content="{{ post.categories.all|join:"," }}">
  {% endif %}
  {% if post.meta_description %}
  <meta name="description" content="{{ post.meta_description }}">
  <meta property="og:description" content="{{ post.meta_description }}">
  {% endif %}
  <meta property="og:title" content="{{ post.title }}">
  {% if post.featured_image %}
  <meta property="og:image" content="{{ request.scheme }}://{{ request.get_host }}{{ post.featured_image.url }}">
  <meta property="og:image:width" content="{{ post.featured_image.width }}">
  <meta property="og:image:height" content="{{ post.featured_image.height }}">
  {% endif %}
  <meta property="og:url" content="{{ request.scheme }}://{{ request.get_host }}{{ request.path }}">
  <meta property="og:site_name" content="{{ site_config.site_name }}">
  <meta property="og:type" content="article">
  <meta name="twitter:card" content="summary_large_image">
  {% blog_json_ld %}
  {% blog_post_json_ld %}
{% endblock meta %}

{% block title %}
<title>{{ post.title }} - {{ site_config.site_name }}</title>
{% endblock title %}

{% block featured_image %}
<style>
  header {
    {% if post.featured_image %}
    background-image: url('{{ post.featured_image.url }}');
    {% else %}
    background-image: url('{% static "bootstrap4_skin/img/featured/post.jpg" %}');
    {% endif %}
  }
</style>
{% endblock featured_image %}

{% block navbar %}
  <div id="fb-root"></div>
  <script>(function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.5";
    fjs.parentNode.insertBefore(js, fjs);
  }(document, 'script', 'facebook-jssdk'));
  </script>
  {{ block.super }} 
{% endblock navbar %}

{% block header %}
<h1 class="display-1">{{ post.title }}</h1>
<p class="font-weight-bold">
  <i class="far fa-calendar-alt"></i>&nbsp;{{ post.date_published}}&nbsp;&nbsp;
  {% if post.allow_comments and site_config.disqus_shortname %}
  <i class="far fa-comment"></i>&nbsp;
  <a href="{{ post.get_absolute_url }}#disqus_thread" class="text-light">{% trans "0 comments" %}</a>
  {% endif %}
</p>
{% endblock header %}

{% block content %}
{% load bootstrap4_skin_tags %}
<div class="col-md col-lg-10 offset-lg-1">
  <article>
    {% if user.is_authenticated %}
    <p>
      <a class="btn btn-light btn-sm" href="/admin/blog/post/{{ post.pk }}/">
        <i class="fas fa-pen-square"></i>&nbsp;{% trans "Edit post" %}
      </a>
    </p>
    {% endif %}
    {{ post.content|safe }}
  </article>
  {% if post.categories.count %}
  <p>
    <small><i class="fas fa-tags"></i>&nbsp;&nbsp;{{ post|render_post_categories|safe }}</small>
  </p>
  {% endif %}
  {% if post.is_published %}
  <p class="social">
    <div class="facebook">
      <div class="fb-share-button" data-href="{{ request.build_absolute_uri }}" data-layout="button"></div>
    </div>
    <div class="linked-in">
      <script src="//platform.linkedin.com/in.js" type="text/javascript"> lang: en_US</script>
      <script type="IN/Share" data-url="{{ request.build_absolute_uri }}"></script>
    </div>
    <div class="twitter">
      <a href="https://twitter.com/share" class="twitter-share-button"{count}>Tweet</a>
      <script>
        !function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';
        if(!d.getElementById(id)){js=d.createElement(s);
          js.id=id;js.src=p+'://platform.twitter.com/widgets.js';
          fjs.parentNode.insertBefore(js,fjs);
        }}(document, 'script', 'twitter-wjs');
      </script>
    </div>
    <div class="reddit">
      <a href="//www.reddit.com/submit" onclick="window.location = '//www.reddit.com/submit?url=' + encodeURIComponent(window.location); return false">
        <img src="//www.redditstatic.com/spreddit7.gif" alt="submit to reddit" border="0" />
      </a>
    </div>
  </p>
  <hr>
  <div class="bottom-box">
    {% if post.allow_comments %}
    {% include "blog/disqus_comments.html" %}
    {% else %}
    <p>Comments are disabled.</p>
    {% endif %}
  </div>
</div>
{% endif %}
{% endblock content %}

{% block footer %}
  {{ block.super }}
  {% if site_config.disqus_shortname %}
  <script id="dsq-count-scr" src="//{{ site_config.disqus_shortname }}.disqus.com/count.js" async></script>
  {% endif %}
{% endblock footer %}

bootstrap4_skin/templates/bootstrap4_skin/blog_posts_list.html
{% extends "bootstrap4_skin/base.html" %}
{% load i18n %}
{% load static %}
{% load blog_tags %}
{% load bootstrap4_skin_tags %}

{% block meta %}
{{ block.super }}
{% if page_title %}
  <meta property="og:title" content="{{ page_title }} - {{ site_config.site_name }}">
{% else %}
  <meta property="og:title" content="{% trans "Home" %} - {{ site_config.site_name }}">
{% endif %}
{% if site_config.featured_image %}
  <meta property="og:image" content="{{ request.scheme }}://{{ request.get_host }}{{ site_config.featured_image.url }}">
  <meta property="og:image:width" content="{{ site_config.featured_image.width }}">
  <meta property="og:image:height" content="{{ site_config.featured_image.height }}">
{% else %}
  <meta property="og:image"
    content="{{ request.scheme }}://{{ request.get_host }}{% static "bootstrap4_skin/img/featured/home.jpg" %}">
  <meta property="og:image:width" content="1280">
  <meta property="og:image:height" content="548">
{% endif %}
  <meta property="og:url" content="{{ request.scheme }}://{{ request.get_host }}{{ request.path }}">
{% if site_config.site_tagline %}
  <meta property="og:description" content="{{ site_config.site_tagline }}">
{% endif %}
  <meta property="og:site_name" content="{{ site_config.site_name }}">
  <meta property="og:type" content="website">
  <meta name="twitter:card" content="summary_large_image">
  {% if post.is_published %}
  {% blog_json_ld %}
  {% endif %}
{% endblock meta %}

{% block title %}
{% if page_title %}
  <title>{{ page_title }} - {{ site_config.site_name }}</title>
{% else %}
  <title>{% trans "Home" %} - {{ site_config.site_name }}</title>
{% endif %}
{% endblock title %}

{% block featured_image %}
<style>
  header {
    {% if "featured" in request.path %}
    background-image: url('{% static "bootstrap4_skin/img/featured/featured.jpg" %}');
    {% elif "categories" in request.path %}
    background-image: url('{% static "bootstrap4_skin/img/featured/categories.jpg" %}');
    {% elif "archive" in request.path %}
    background-image: url('{% static "bootstrap4_skin/img/featured/archive.jpg" %}');
    {% elif site_config.featured_image %}
    background-image: url('{{ site_config.featured_image.url }}');
    {% else %}
    background-image: url('{% static "bootstrap4_skin/img/featured/home.jpg" %}');
    {% endif %}
  }
  </style>
{% endblock featured_image %}


{% block header %}
{% if page_title %}
  <h1 class="display-1">{{ page_title }}</h1>
{% else %}
  <h1 class="display-1">{{ site_config.site_name }}</h1>
  <h2>{{ site_config.site_tagline }}</h2>
{% endif %}
{% endblock header %}

{% block content %}

  <div class="col-md-8 col-lg-7 offset-lg-1">
    {% block blog_list %}
    {% for post in posts %}
    <div class="card mb-3">
      <a href="{{ post.get_absolute_url }}">
        {% if post.featured_image %}
        <img class="card-img-top" src="{{ post.featured_image.url }}" alt="{% trans "Featured Image" %}">
        {% else %}
        <img class="card-img-top" src="{% static "bootstrap4_skin/img/featured/post.jpg" %}" alt="{% trans "Featured Image" %}">
        {% endif %}
      </a>
      <div class="card-body">
        <h3 class="card-title text-uppercase">
          <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </h3>
        <p>
          <small class="text-muted">
            <i class="far fa-calendar-alt"></i>&nbsp;{{ post.date_published }}&nbsp;
            {% if post.allow_comments and site_config.disqus_shortname %}
            <i class="far fa-comment"></i>&nbsp;
            <a href="{{ post.get_absolute_url }}#disqus_thread">{% trans "0 comments" %}</a>&nbsp;
            {% endif %}
            {% if user.is_authenticated %}
            <a class="btn btn-light btn-sm" href="/admin/blog/post/{{ post.pk }}/">
              <i class="fas fa-pen-square"></i>&nbsp;{% trans "Edit post" %}
            </a>
            {% endif %}
          </small>
        </p>
        <div class="post-cut">{{ post|truncate_post|safe }}</div>
        <p><a href="{{ post.get_absolute_url }}" class="btn btn-secondary">{% trans "Read post" %}</a></p>
        {% if post.categories.count %}
        <p>
          <small>
            <i class="fas fa-tags"></i>&nbsp;{{ post|render_post_categories|safe }}
          </small>
        </p>
        {% endif %}
      </div>
    </div>
    {% empty %}
      <h3 class="text-danger">{% trans "This section has no posts." %}</h3>
    {% endfor %}

    {% if is_paginated %}
    <nav class="pager d-flex justify-content-between mb-3">
      <a href="{{ request.path }}{% if page_obj.has_next %}?page={{ page_obj.next_page_number }}{% endif %}"
          class="btn btn-secondary {% if not page_obj.has_next %}disabled{% endif %}">
        <i class="fas fa-arrow-left"></i>&nbsp;{% trans "Older" %}
      </a>
      <a href="{{ request.path }}{% if page_obj.has_previous %}?page={{ page_obj.previous_page_number }}{% endif %}"
          class="btn btn-secondary {% if not page_obj.has_previous %}disabled{% endif %}">
        {% trans "Newer" %}&nbsp;<i class="fas fa-arrow-right"></i>
      </a>
    </nav>
    {% endif %}
    {% endblock blog_list %}

  </div>
  {# End posts list #}
  {# Side panel #}
  <div class="col-md-4 col-lg-3">

    <form class="form-inline mb-3" method="get" action="{% url "blog:search" %}">
      <div class="input-group">
        <input class="form-control" type="search" name="q" value="{{ query }}" placeholder="{% trans "Search" %}">
        <div class="input-group-append">
          <button class="btn btn-secondary" type="submit"><i class="fas fa-search"></i></button>
        </div>
      </div>
    </form>

    {% if user.is_authenticated %}
    <div class="card mb-3">
      <div class="card-body">
        <h5 class="card-title text-uppercase"><i class="fas fa-cogs"></i></i>&nbsp;{% trans "Blog Admin" %}</h5>
        <hr>
        <ul class="list-unstyled ml-2">
          <li>
            <a href="/admin/blog/post/add"><i class="fas fa-pen-square"></i>&nbsp;{% trans "New Post" %}</a>
          </li>
          <li>
            <a href="/admin/blog/post"><i class="far fa-copy"></i>&nbsp;{% trans "Manage Posts" %}</a>
          </li>
          <li>
            <a href="/admin"><i class="fas fa-bars"></i>&nbsp;{% trans "Admin Panel" %}</a>
          </li>
          <li>
            <a href="/admin/logout"><i class="fas fa-sign-out-alt"></i>&nbsp;{% trans "Logout" %}</a>
          </li>
        </ul>
      </div>
    </div>
    {% endif %}

    {% get_posts_digest True 3 as featured_posts %}
    {% if featured_posts.objects %}
    <div class="card mb-3">
      <div class="card-body">
        <h5 class="card-title text-uppercase"><i class="far fa-star"></i>&nbsp;{% trans "Featured Posts" %}</h5>
        <hr>
        <ul class="list-unstyled ml-2">
          {% for post in featured_posts.objects %}
          <li>
            <p>
              <a href="{{ post.get_absolute_url }}">{{ post.title }}</a><br>
              <small class="text-muted"><i class="far fa-calendar-alt"></i>&nbsp;{{ post.date_published }}</small>
          </p>
          </li>
          {% endfor %}
        </ul>
        {% if featured_posts.more %}
        <a href="{{ featured_posts.more }}" class="card-link">{% trans "More..." %}</a>
        {% endif %}
      </div>
    </div>
    {% endif %}

    {% get_categories as categories %}
    {% if categories %}
    <div class="card mb-3">
      <div class="card-body">
        <h5 class="card-title text-uppercase"><i class="fas fa-tags"></i>&nbsp;{% trans "Categories" %}</h5>
        <hr>
        <ul class="list-unstyled ml-2">
          {% for category in categories %}
          <li>
            <a href="{{ category.get_absolute_url }}">
              {{ category.name }}&nbsp;<span class="badge badge-secondary">{{ category.get_published_posts_count }}</span>
            </a>
          </li>
          {% endfor %}
        </ul>
      </div>
    </div>
    {% endif %}

    {% get_archive_digest 6 as months %}
    {% if months %}
    <div class="card mb-3">
      <div class="card-body">
        <h5 class="card-title text-uppercase"><i class="fas fa-archive"></i>&nbsp;{% trans "Archive" %}</h5>
        <hr>
        <ul class="list-unstyled ml-2">
          {% for month in months.objects %}
          <li>
            <a href="{% url "blog:month_archive" year=month.year month=month.month %}">{{ month|date:"F Y" }}</a>
          </li>
          {% endfor %}
        </ul>
        {% if months.more %}
        <a href="{% url "blog:archive" %}" class="card-link">{% trans "More..." %}</a>
        {% endif %}
      </div>
    </div>
    {% endif %}
  </div>
  {# End side panel #}
{% endblock content %}

{% block footer %}
  {{ block.super }}
  {% if site_config.disqus_shortname %}
  <script id="dsq-count-scr" src="//{{ site_config.disqus_shortname }}.disqus.com/count.js" async></script>
  {% endif %}
{% endblock footer %}

bootstrap4_skin/templates/bootstrap4_skin/paginator.html
<div class="btn-group" role="group">
  {% if has_previous %}
     <a class="btn btn-secondary" href="{{ request.path }}?q={{ query }}&page={{ previous }}"><i class="fas fa-angle-left"></i></a>
  {% else %}
     <button type="button" class="btn btn-secondary" disabled="disabled"><i class="fas fa-angle-left"></i></button>
  {% endif %}

  {% if show_first %}
     <a class="btn btn-secondary" href="{{ request.path }}?q={{ query }}&page=1">1</a>
     <button type="button" class="btn btn-secondary" disabled="disabled">...</button>  
  {% endif %}

  {% for linkpage in page_numbers %}
    {% ifequal linkpage page %}
       <button type="button" class="btn btn-secondary active" >{{ page }}</button>
    {% else %}
       <a class="btn btn-secondary" href="{{ request.path }}?q={{ query }}&page={{ linkpage }}">{{ linkpage }}</a>
    {% endifequal %}
  {% endfor %}

  {% if show_last %}
     <button type="button" class="btn btn-secondary" disabled="disabled">...</button>
     <a class="btn btn-secondary" href="{{ request.path }}?q={{ query }}&page=last">{{ pages }}</a>
  {% endif %}

  {% if has_next %}
     <a class="btn btn-secondary" href="{{ request.path }}?q={{ query }}&page={{ next }}"><i class="fas fa-angle-right"></i></a>
  {% else %}
     <button type="button" class="btn btn-secondary" disabled="disabled"><i class="fas fa-angle-right"></i></button>
  {% endif %}
</div>